CREATE TABLE `orders` (
	`Order_ID` INT(10) NOT NULL AUTO_INCREMENT,
	`Customer_ID` INT(10) NOT NULL,
	`ProductType_ID` INT(10) NOT NULL,
	`Order_Time` DATETIME(5) NOT NULL DEFAULT CURRENT_TIMESTAMP(5),
	PRIMARY KEY (`Order_ID`) USING BTREE
)
COMMENT='Order  Details'
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;